Adding binaries, sensors, and battery - Separating devices
ymerj/HE-HA-control pull request #44
Opened 2022-01-19 18:04 UTC by doonce

Repost of PR#41

I did my best to compare the binary sensors within HA and match them up with their Hubitat counterparts. I had to take a new direction in translating devices since there is a "lock" device and "lock" binary_sensor, so it will now look based on domain as well as device_class. Binary sensor classes are [here](https://www.home-assistant.io/integrations/binary_sensor/), sensor classes are [here](https://www.home-assistant.io/integrations/sensor#device-class), and it will assume other things are devices.

There are a few HA binary sensors that **should** work in Hubitat, but there isn't a Generic Component available including gas sensor, sound sensor, tamper sensor, light sensor (also conflicts with light device, another reason I separated), etc. However, a lot of these can be hacked into use by just setting them as motion sensors or another Generic Binary Component, but I didn't want to do that here.

Everything I added has been tested using template devices in HA.

2022-01-19 18:07 UTC, doonce commented
I do still think removing whitespace is important, but I have left it out of this PR for now. Also, as I mentioned in the HE forums, it is possible to add some additional missing generic component devices to add support of HA devices in HE like I have done here with Battery.

2022-02-18 14:53 UTC, tomwpublic requested changes

2022-02-18 14:53 UTC, tomwpublic commented on HA parent.groovy
> +* 0.1.38 2022-01-19 BrenenP            Added support for additional sensors
Please update to version 0.1.39.

2022-02-18 14:53 UTC, tomwpublic commented on genericComponentBattery.groovy
> +0.1.13- @tomw - initial version
Please update to version 0.1.39 and attribute to BrenenP.

2022-02-18 14:53 UTC, tomwpublic commented on genericComponentBattery.groovy
> +Copyright 2021
Please add this file as an optional component in packageManifest.json. 'id' is just a random GUID.  Also update to version 0.1.39 in packageManifest.json

2022-02-18 14:53 UTC, tomwpublic commented on HA parent.groovy
> +def translateDevices(device_class, newVals, friendly, origin)
Rename device_class parameter to domain for clarity.

2022-02-22 18:39 UTC, merged